[build]
command = "nuxt build && nuxt export"
publish = "dist"

[context.production]
command = "BASE_URL=$URL nuxt build && nuxt export"

[context.deploy-preview]
command = "BASE_URL=$DEPLOY_PRIME_URL nuxt build && nuxt export"
